apiVersion: postgresql.cnpg.io/v1
kind: Pooler

metadata:
  name: ayoob-ro-pooler
  namespace: ayoob-k-ibrahim

spec:
  cluster:
    name: ayoob-postgres

  instances: 2

  type: ro

  pgbouncer:
    poolMode: transaction

    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
