apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ayoob-cnpg-alerts
  namespace: ayoob-k-ibrahim
  labels:
    release: ayoob-prometheus-stack
spec:
  groups:
    - name: cnpg-ayoob
      rules:
        - alert: CNPGStreamingReplicasLow
          expr: max(cnpg_pg_replication_streaming_replicas{namespace="ayoob-k-ibrahim", cluster="ayoob-postgres"}) < 2
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Fewer than 2 streaming replicas on {{ $labels.cluster }}"

        - alert: CNPGReplicationLagHigh
          expr: cnpg_pg_replication_lag{namespace="ayoob-k-ibrahim", cluster="ayoob-postgres"} > 30
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Replication lag {{ $value }}s on {{ $labels.pod }}"

        - alert: CNPGBackupStale
          expr: (time() - cnpg_collector_last_available_backup_timestamp{namespace="ayoob-k-ibrahim", cluster="ayoob-postgres"}) > 86400
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "No recent backup for cluster {{ $labels.cluster }}"