grafana:
  enabled: true

  adminPassword: prom-operator

  defaultDashboardsEnabled: true

  persistence:
    enabled: false

  service:
    type: ClusterIP

  sidecar:
    dashboards:
      enabled: false

    datasources:
      enabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://ayoob-prometheus-stack-kub-prometheus.ayoob-monitoring:9090
          isDefault: true

  nodeSelector:
    kubernetes.io/hostname: k3s-kubenine-intern-3048-ed140f-node-pool-0576-9nfz5

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 256Mi

prometheus:
  prometheusSpec:
    retention: 2d

    scrapeInterval: 30s

    nodeSelector:
      kubernetes.io/hostname: k3s-kubenine-intern-3048-ed140f-node-pool-0576-9nfz5

    resources:
      requests:
        cpu: 150m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 1Gi

alertmanager:
  enabled: false

kube-state-metrics:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheusOperator:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

nodeExporter:
  enabled: true

prometheus-node-exporter:
  hostNetwork: false
  hostPID: false
  hostPort: null
  service:
    port: 9100
    targetPort: 9100
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
