apiVersion: cert-manager.io/v1
kind: ClusterIssuer

metadata:
  name: task-2-51-cluster-issuer

spec:
  acme:
    email: ayoobkibrahim01@gmail.com

    server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: task-2-51-cluster-issuer-key

    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: task-2-51-cloudflare-api-token-secret
              key: api-token