apiVersion: v1
kind: Service
metadata:
  name: task-2-37-clusterip
  namespace: ayoob-k-ibrahim
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
