apiVersion: v1
kind: Pod
metadata:
  name: task-2-43-huge-request-pod
  namespace: ayoob-k-ibrahim
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "10"
        memory: "20Gi"
