apiVersion: v1
kind: Pod
metadata:
  name: task-2-43-guaranteed-pod
  namespace: ayoob-k-ibrahim
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
