apiVersion: v1
kind: Pod
metadata:
  name: task-2-43-oom-test-pod
  namespace: ayoob-k-ibrahim
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
