apiVersion: v1
kind: Pod
metadata:
  name: task-2-46-pending
  namespace: ayoob-k-ibrahim
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "500Gi"
        cpu: "100"
